apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexride-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flexride-api-gateway
  template:
    metadata:
      labels:
        app: flexride-api-gateway
    spec:
      containers:
        - name: api-gateway
          image: flexride/api-gateway:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flexride-api-gateway
spec:
  selector:
    app: flexride-api-gateway
  ports:
    - port: 80
      targetPort: 3000
